### ISSUE TITLE
utf8 activity are not converted correctly

### ISSUE THREAD

**Issue by xieofxie** [Azure-Samples/Cognitive-Services-Direct-Line-Speech-Client#49]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

Send an activity contains special characters like ⭐ from bot.

### Any log messages given by the failure
>

It is converted to Unicode of default encoding, so it is not ⭐ any more.

### Expected/desired behavior
>

Convert correctly.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

Windows 10.

### Versions
>

Latest master.

### Mention any other details that might be useful

It might not be fixed here as activity comes from Microsoft.CognitiveServices.Speech.Dialog.DialogServiceConnector.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by dargilco** [comment]
@xieofxie, thanks for reporting this! it's a bug in Speech SDK, known and tracked. I'll resolve this issue one it is fixed in Speech SDK and Direct Line Speech Client is updated to consume the Speech SDK NuGet with the fix.

**Comment by dargilco** [comment]
This is fixed in Speech SDK 1.8, and Direct Line Speech Client was recently updated to use Speech SDK 1.8.

**Comment by xieofxie** [comment]
Hi, @dargilco the speech key is not shown any more in channel, could you help?
![image](https://user-images.githubusercontent.com/2876650/69021010-608f6500-09f1-11ea-8fb2-a1dadd194bd5.png)

**Comment by dargilco** [comment]
@xieofxie, You first need to [Create a Speech resource in Azure](https://docs.microsoft.com/en-us/azure/cognitive-services/Speech-Service/get-started#create-a-speech-resource-in-azure). Once you created it, it should show up in the drop down selection you marked in red ("Cognitive service account"). 
Thanks,
Darren

**Comment by xieofxie** [comment]
@dargilco Yes, I have created resource (I just marked it to hide the name..). However, after selecting it, no bot secret is shown below as before. Where should I find the secret? Thanks~

**Comment by dargilco** [comment]
@xieofxie, with Speech SDK 1.8 you no longer need a "bot secret". The only thing your client application needs is the speech key (or a token substitute), and the key region.  See [BotFrameworkConfig](https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.dialog.botframeworkconfig?view=azure-dotnet) Class, and the source code of this tool.

**Comment by xieofxie** [comment]
Thanks! @dargilco I should have updated this repo first. Bot secret is no longer shown in UI..
