### ISSUE TITLE
Direct Line Speech Channel through REST?

### ISSUE THREAD

**Issue by mindlessroman** [Azure-Samples/Cognitive-Services-Direct-Line-Speech-Client#52]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> 
### Any log messages given by the failure
>

### Expected/desired behavior
> Have a REST API exposed? Or document what is needed for Direct Line Speech channel in terms of a token/URL/etc? Or SDK for more languages than just C#? Any of the above would be amazingly helpful.

### OS and Version?
> Windows 10, Android emulation API 28

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by dargilco** [comment]
The [Resources section](https://github.com/Azure-Samples/Cognitive-Services-Direct-Line-Speech-Client#resources) in README.md has links that should answer your questions. 
Client application uses Speech SDK to connect to Direct Line Speech channel. This is a websocket connection, optimized for streaming real-time audio up and down. There are no REST APIs.
Darren
