### ISSUE TITLE
Error : Cannot access a closed Stream 

### ISSUE THREAD

**Issue by diana-RC** [Azure-Samples/Cognitive-Services-Direct-Line-Speech-Client#54]
### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>I am following the below document 
https://docs.microsoft.com/bs-latn-ba/azure/cognitive-services/speech-service/tutorial-voice-enable-your-bot-speech-sdk
I have tried it with the echo bot and I have followed all the steps and have created all the resources as said in the document. The Direct line speech client is actually saying "Hello and Welcome". And when I press the microphone and if I speak something it is raising an exception in 
ProduceConsumerStream.cs line 110

and if I press continue then it just echoes the text message but it is not speaking.
I have not changed any thing in the code

### Any log messages given by the failure
>System.ObjectDisposedException
HResult=0x80131622
Message=Cannot access a closed Stream.
Source=mscorlib
StackTrace:
at System.IO.__Error.StreamIsClosed()
at System.IO.MemoryStream.set_Position(Int64 value)
at DLSpeechClient.ProducerConsumerStream.Write(Byte[] buffer, Int32 offset, Int32 count) in C:\Users\diana\Cognitive-Services-Direct-Line-Speech-Client\DLSpeechClient\ProducerConsumerStream.cs:line 110
at DLSpeechClient.MainWindow.<>c__DisplayClass40_1.<Connector_ActivityReceived>b__4() in C:\Users\diana\Cognitive-Services-Direct-Line-Speech-Client\DLSpeechClient\MainWindow.xaml.cs:line 362
at System.Threading.Tasks.Task.Execute()

### Expected/desired behavior
>The echo Bot should speak the echo text but when I start the application it says "Hello and welcome" but after that when I speak it goes to exception and when I continue it just prints the echo text. No voice after the welcome echo.

### OS and Version?
> Windows 10
### Versions
>
I am using virtual assistant Bot Builder SDK v4
### Mention any other details that might be useful

I have created all the azure resources in west europe and speech instance in west europe.

I would also like to have any documentation of how to integrate the virtual assistant to Direct Line Speech Client.
Please advice
Thank you

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by diana-RC** [comment]
Thanks a lot @nrobert it fixed my issue and it is working fine. Any pointers to how to integrate virtual assistant to Direct Line Speech Client pls.
Thank you so much

**Comment by nrobert** [comment]
Hi @diana-RC , I guess this tutorial is for you: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/tutorial-voice-enable-your-bot-speech-sdk

**Comment by diana-RC** [comment]
Thank you @nrobert. I am following the same document but will virtual assistant bot work ?if I follow the same instruction? pls advice

As they have explained with echo bot .
pls advice

**Comment by dargilco** [comment]
@diana-RC , I believe this is what you are looking for: "[Tutorial: Enable Speech for your Assistant](https://microsoft.github.io/botframework-solutions/tutorials/enable-speech/1_intro/)"
