### ISSUE TITLE
Connection Failure

### ISSUE THREAD

**Issue by Vishallavania** [Azure-Samples/Cognitive-Services-Direct-Line-Speech-Client#64]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [x] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>As mentioned in the doc provided by you. I have entered both subscription key and subscription region exactly mentioned on the azure portal but still it is showing same error again and again,

Error:
ConnectionFailure : Connection failed (no connection to the remote host). 
Internal error: 1. Error details: 11001. Please check network connection, firewall setting, and the region name used to create speech factory. SessionId: 5abc48b3c1a04ba7ac85b5d561d6a8b5

I have used the key and region name in one of console app intend to so STT,TTS and intent recognition. It is working fine there.

### OS and Version?
> Windows 10

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by dargilco** [comment]
@Vishallavania If it were an issue with your key or key-region, there will be an authentication error. This error is related to network connection (firewall settings and such). Are you able to use [Bot-Framework Emulator](https://github.com/Microsoft/BotFramework-Emulator) and do a chat with your Bot hosted as a service? (after registering it with Direct Line channel).

**Comment by Vishallavania** [comment]
Hi Darren,

Yes i am able to use my bot hosted as a service and also key and key
regions are exact i have cross checked from the portal.

**Comment by dargilco** [comment]
@Vishallavania can you share a log file while you see the error? Enter a text file name in the "Log file path" field in the settings page. These are Speech SDK logs. Logs are appended to the log file each time you run the tool, so make sure you delete the log file before you start your run. Note that the log is usually very verbose, but since you see the error right at the beginning I'm hoping it would be short. Try to paste the log lines as a reply in this thread. If it's too long, please share it on some public storage site so I can grab it. Thanks!
Darren

**Comment by Vishallavania** [comment]
Hi Darren,

Please find the log file link below:
https://drive.google.com/open?id=1S2PZn6SCCGJPNfYUEzieROmXZN5ZTqdc

Regards
Vishal

**Comment by dargilco** [comment]
@Vishallavania from the logs I see your speech key is for the Azure region "southcentralus". Direct Line Speech channel is not yet supported in this region. See this [Voice Assistants](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/regions#voice-assistants) table for the supported Azure regions. Please try with a supported region and let me know if that works. Thanks!
Darren

**Comment by Vishallavania** [comment]
Hi Darren,

I have made a fresh speech service with eastus as a region but still i am
getting same error. Please have a look on new log file i have attached
below for your reference.

https://drive.google.com/file/d/1OKvciedc77_yNBv-soP_Qiwt0a7njw7e/view?usp=drivesdk

**Comment by dargilco** [comment]
@Vishallavania I requested access to the link.

**Comment by Vishallavania** [comment]
grant access already..please check

**Comment by dargilco** [comment]
Thanks, looking at it now.

**Comment by dargilco** [comment]
_"WebSocket Upgrade failed with an authentication error (401). Please check for correct subscription key (or authorization token) and region name"._ 
How did you get the speech subscription key?  It should be a Cognitive Services Speech key. 
https://portal.azure.com/ ==> "Create a resource" ==> Search for "Speech". The Azure resource is named "Speech". The key you need to provide is one of the two keys (KEY 1, KEY 2) listed on the left blade in your Speech under "Keys".

**Comment by Vishallavania** [comment]
Ya, in similar way i have been creating it.

**Comment by dargilco** [comment]
Are you able to text-chat with your bot using the chat tool in the Azure portal, Bot Channels Registration resource, under "Test in web chat"?
In the "Bot Channels Registration" Azure resource, is the Enabled Streaming Endpoint box checked? (under "Settings").
In your "App Service" Azure resource -> Configuration -> "General Settings" tab, is "Web Sockets" turned on?
In your "Bot Channels Registration" Azure resource -> Channels, are you seeing any "Health" issues in red, related to Web Chat or Direct Line Speech channels? When you click on the red issues it will pop up a window showing some error details. What do you see there?
Thanks,
Darren
