### ISSUE TITLE
Connectionproblem to DirectLine Speech Channel and Bot

### ISSUE THREAD

**Issue by rayburks** [Azure-Samples/Cognitive-Services-Direct-Line-Speech-Client#66]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Use the DLSpeechClient to connect this client with my bot, but got always an 404 Response connecting the Directline Speech Api Channel:

Error ConnectionFailure : Connection was closed by the remote host. Error code: 1002. Error details: The server returned status code '404' when status code '101' was expected. SessionId: d008b5f52e334e91b267034a122eaf51

### Any log messages given by the failure
>Infos from speech log file:
wss://westus.convai.speech.microsoft.com/api/v3?language=en-US
(419): 31096ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:119 Microsoft::CognitiveServices::Speech::Impl::ISpxPropertyBagImpl::LogPropertyAndValue: this=0x0D90A334; name='SPEECH-ConnectionUrl'; value='wss://westus.convai.speech.microsoft.com/api/v3?language=en-US'
(419): 31096ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:979 speech.config {"context":{"audio":{"source":{"bitspersample":"16","channelcount":"1","model":"Headset Microphone (Jabra BIZ 2400 II)","samplerate":"16000","type":"Microphones"}},"os":{"name":"Client","platform":"Windows","version":"8"},"system":{"build":"Windows-x86","lang":"C#","name":"SpeechSDK","version":"1.9.0"}}}

....

(419): 32731ms SPX_TRACE_ERROR:  usp_reco_engine_adapter.cpp:1734 Response: On Error: Code:5, Message: Connection was closed by the remote host. Error code: 1002. Error details: The server returned status code '404' when status code '101' was expected..

Infos from Loganalytics and Speechservice:

{"parsedStack":[{"assembly":"Microsoft.Bot.Base.ChannelConnector, Version=3.2.3.9, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Bot.ChannelConnector.BotAPI+<PostActivityToBotViaSocketAsync>d__34.MoveNext","level":0,"line":0}],"outerId":"0","message":"POST to dianachannels failed: The server returned status code '404' when status code '101' was expected.","type":"Microsoft.Bot.Schema.BotException","id":"33867562"}

### Expected/desired behavior
>Connection to the Bot

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 10
### Versions
>Version	10.0.17763 Build 17763

### Mention any other details that might be useful

- followed very detailed all steps in the tutorial https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/tutorial-voice-enable-your-bot-speech-sdk
- I tried a speechservice running in West US and Westeurope.
- Websockets for the Messageendpoint and Bot are enabled.
- Enable Streaming Endpoint is enabled in the Channel Bot Registration.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by rayburks** [comment]
- Logfile from Client
[speech_1.log](https://github.com/Azure-Samples/Cognitive-Services-Direct-Line-Speech-Client/files/4186487/speech_1.log)
![dlspeechclient_problem](https://user-images.githubusercontent.com/9565902/74251693-ccc9ee00-4cec-11ea-92ca-7f1a403060aa.PNG)

**Comment by chschrae** [comment]
@rayburks Hi there,

Are you able to connect to your bot using the bot framework emulator? https://github.com/Microsoft/BotFramework-Emulator
You would need to install ngrok as well which has instructions here:
https://github.com/Microsoft/BotFramework-Emulator/wiki/Tunneling-(ngrok)

That will test your bot without using the Direct line speech channel.

Another thing you can check if you have it hooked up is any app insights messages or if you view your "Bot Channels Registration" azure object and go to the "Channels" blade, are there any issues there? It would look something like this...
![image](https://user-images.githubusercontent.com/32145632/74270860-bf970a00-4cc0-11ea-9f01-76fa56ecaff8.png)

**Comment by rayburks** [comment]
Hi, thx for the info.

yes Bot works in WebChat, DitectLine, in Teams and Emulator.

![directline](https://user-images.githubusercontent.com/9565902/74309864-11489e80-4d6c-11ea-8f5b-d5700ea6de75.png)

But one question: my Bot has an AppId and AppPassword. The bot channel generates an ServicePrincipal to secure the connected Bot by default. 
The tutorial described above, explains that the AppId and AppPassword should be ignored
and don't use an AppID and AppPassword to protect the access to the bot message endpoint. 
Could that be the reason?

**Comment by rayburks** [comment]
Solved the problem by myself. It was a problem with the bot. Changed the BotFrameworkHttpAdapter and could reach the bot. DL Client works perfectly and problem is solved.

Thx in advance.

**Comment by chschrae** [comment]
Great! Glad it all worked out for you.

If you have the time, could you tell me more specifically what you changed it from and to? In case someone else has the same issue.

**Comment by dannybergs** [comment]
> Solved the problem by myself. It was a problem with the bot. Changed the BotFrameworkHttpAdapter and could reach the bot. DL Client works perfectly and problem is solved.
> 
> Thx in advance.

Hey rayburks,

we faced the same problem as you. Could you maybe go a little bit into detail about your solution?

greetings
danny
