### ISSUE TITLE
Connection Failure: Error Code: 1011 System.NullReferenceException

### ISSUE THREAD

**Issue by sebnema** [Azure-Samples/Cognitive-Services-Direct-Line-Speech-Client#69]
Hi,
I am having a connection failure exception when I run Virtual assistant sample project and set the language as Turkish.  

Sample project link: https://github.com/Azure-Samples/Cognitive-Services-Voice-Assistant/tree/master/clients/csharp-wpf

The error occurs right after I click on Reconnect. 
I don’t see any error on bot side or in Application insights logs. I am guessing it is returning from Directline speech client connector (see the picture down below).
When I changed the language to en-US. The error goes away. But my bot text is in Turkish, so practically it doesn't work :)

I followed the steps in the article below. I set the app service configurations and changed my bot code as defined in the article. 
https://docs.microsoft.com/en-us/azure/bot-service/directline-speech-bot?view=azure-bot-service-4.0

I can send you my keys to try if you need to. 

Any help is appreciated. 

![image](https://user-images.githubusercontent.com/10426499/78921909-52280f80-7a9e-11ea-8599-359532018044.png)

This is the error in Bot channel.

![image](https://user-images.githubusercontent.com/10426499/78922017-826fae00-7a9e-11ea-82fa-9f4ef8466280.png)

Thanks.

**Comment by chschrae** [comment]
Hi there! Thanks for reaching out.

I will start trying to reproduce this. It does seem if you are getting a message in the bot channel that there is an issue in the Direct Line Speech Channel.

Can you share the logfile you are collecting? This could help us track the issue down.

Also can you share exactly what configuration you are running? x86 or x64? Debug or Release?

**Comment by chschrae** [comment]
@sebnema Also can you create an azure support ticket for this?

**Comment by sebnema** [comment]
> Hi there! Thanks for reaching out.
> 
> I will start trying to reproduce this. It does seem if you are getting a message in the bot channel that there is an issue in the Direct Line Speech Channel.
> 
> Can you share the logfile you are collecting? This could help us track the issue down.
> 
> Also can you share exactly what configuration you are running? x86 or x64? Debug or Release?
Hi Chris, 
Thanks for the response. Pfa log file.  
[log.txt](https://github.com/Azure-Samples/Cognitive-Services-Direct-Line-Speech-Client/files/4458024/log.txt)

and here is my bot publish settings: 
![image](https://user-images.githubusercontent.com/10426499/78929565-4c84f680-7aab-11ea-835b-c355f7616575.png)

Thanks.

**Comment by sebnema** [comment]
> @sebnema Also can you create an azure support ticket for this?

Hi Chris,
I created the ticket #120040921001987. 

Thx.

**Comment by chschrae** [comment]
@sebnema I have talked to the Direct Line Speech team and discovered that the turkish language is not currently supported. They have added it as an internal work item but are unable to provide an estimate of when it will be supported.

They have committed to updating this doc with a new section for voice assistants
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support

So you can check that link periodically to see when it gets supported.

I'm sorry, I know this isn't the answer you were hoping for.

**Comment by sebnema** [comment]
Hi Christopher,
Thanks for the information.
Could you please let me know why the connector is language dependent?

Because there is turkish support for both speech to text and text to speech?

I couldn't understand this dependency.

Thanks,
Şebnem

Sent from Outlook<https://aka.ms/qtex0l> for iOS
________________________________

**Comment by sebnema** [comment]
> @sebnema I have talked to the Direct Line Speech team and discovered that the turkish language is not currently supported. They have added it as an internal work item but are unable to provide an estimate of when it will be supported.
> 
> They have committed to updating this doc with a new section for voice assistants
> https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support
> 
> So you can check that link periodically to see when it gets supported.
> 
> I'm sorry, I know this isn't the answer you were hoping for.


Hi Christopher,
Thanks for the information.
Could you please let me know why the connector is language dependent?

Because there is turkish support for both speech to text and text to speech?

I couldn't understand this dependency.

Thanks.

**Comment by chschrae** [comment]
@sebnema 
Sure thing. The Direct Line Speech service is what the DialogServiceConnector connects to. This service is separate from the Speech service that the recognizer connects to. The Direct Line Speech facilitates full conversations and the use of bots whereas the simple speech service simply does Speech to Text or if you are hitting the Text to Speech service then Text to Speech.

There is some integration work that needs to happen on the Direct Line Speech service before it is available there.
